version: '{build}'

image: Visual Studio 2017

init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\$env:TARGET\craft\bin\craft.py" $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 git://anongit.kde.org/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & C:\python36\python.exe C:\CraftMaster\CraftMaster\CraftMaster.py --config $env:APPVEYOR_BUILD_FOLDER\.appveyor.ini --target $env:TARGET
    craft --add-blueprint-repository https://github.com/quassel/craft-blueprints-quassel.git
    craft -p quassel/quassel
    craft nsis
    craft --install-deps quassel/quassel

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER quassel/quassel

test_script:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test quassel/quassel

on_success:
- ps: |
    craft --src-dir $env:APPVEYOR_BUILD_FOLDER --package quassel/quassel
    Get-ChildItem C:\CraftMaster\$env:TARGET\tmp\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

environment:
    matrix:
    - TARGET: windows-msvc2017_64-cl
    - TARGET: windows-msvc2017_32-cl
