// Versioning, should be kept current :)
// This is included in main.cpp

{ using namespace Global;

  quasselVersion = "0.2.0-alpha3-pre";
  quasselDate = "2008-03-10";
  quasselBuild = 624;

  //! Minimum client build number the core needs
  clientBuildNeeded = 620;
  clientVersionNeeded = quasselVersion;

  //! Minimum core build number the client needs
  coreBuildNeeded = 620;
  coreVersionNeeded = quasselVersion;

}
