// Versioning, should be kept current :)
// This is included in main.cpp

{ using namespace Global;

  quasselVersion = "0.2.0-pre";
  quasselDate = "2008-02-01";
  quasselBuild = 430;

  //! Minimum client build number the core needs
  clientBuildNeeded = 428;
  clientVersionNeeded = quasselVersion;

  //! Minimum core build number the client needs
  coreBuildNeeded = 428;
  coreVersionNeeded = quasselVersion;

}
