// Versioning, should be kept current :)
// This is included in main.cpp

{ using namespace Global;

  quasselVersion = "0.2.0-pre";
  quasselDate = "2008-02-05";
  quasselBuild = 461;

  //! Minimum client build number the core needs
  clientBuildNeeded = 461;
  clientVersionNeeded = quasselVersion;

  //! Minimum core build number the client needs
  coreBuildNeeded = 461;
  coreVersionNeeded = quasselVersion;

}
