######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 13 23:13:40 2007
######################################################################

TEMPLATE = app
DESTDIR = .
INCLUDEPATH = ../../src/curses/
LIBS += -L../../deploy/libs -lQxtCurses -lQxtCore -lQxtKit
TARGET = QxtCursesTest

# Input
SOURCES += cursestest.cpp
HEADERS += cursestest.h
CONFIG += qxt
QXT += curses core kit
